######################################################################
# Automatically generated by qmake (2.01a) ven. mai 22 13:10:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += MainWindow.ui untitled.ui
SOURCES += fredmain.cpp
