#!/bin/tcsh
echo "I need to INSERT an INITIAL BALANCE"
mysql -u root -pfred1301 << EOF
use managementoverview;
truncate cashflows;
commit;
EOF
echo "Chargement de CA20150719"
cd /home/frederickerdraon/Documents/researchwork/Perl/
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20150719_1114.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
echo "Chargement de CA20121108"
#perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20121108_2009.txt 2012
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
echo "Chargement de CA20131029"
#perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20131029_1236.txt 2013
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
echo "Chargement de CA20150724_1659.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20150724_1659.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
cp -p /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows-cmb.csv /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
mysql -u root -pfred1301 -D managementoverview < /home/frederickerdraon/Documents/researchwork/Sql/MysqlUpdateCategories.sql
echo "Chargement de CA20150801_0844.txt"
#sed "s/\$//g" /home/frederickerdraon/Documents/researchwork/Data/CA20150801_0844.txt 
#sed "s/ //g" /home/frederickerdraon/Documents/researchwork/Data/CA20150801_0844.txt 
#sed "s/é/e/g" /home/frederickerdraon/Documents/researchwork/Data/CA20150801_0844.txt 
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20150801_0844.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20150823_0102.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20150823_0102.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20151029_0102.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20151027_1739.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

#echo "Chargement de CA20151027_1739.txt"
#perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20151027_1739.txt 2015
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20151128_2133.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20151128_2133.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20151222_1615.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20151222_1615.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160103_2243.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160103_2243.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160403_0935.txt"
#sed "s/\$//g" /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt > /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt
#sed "s/ //g" /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt > /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt
#sed "s/é/e/g" /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt > /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160403_0935.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160108_1102_2015.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160108_1102_2015.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160108_1102_2016.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160108_1102_2016.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160112_1933_2015.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160112_1933_2015.txt 2015
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160112_1933_2016.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160112_1933_2016.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160417_1907.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160417_1907.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160808_1522.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160808_1522.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20160829_1305.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20160829_1305.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20161008_2224.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20161008_2224.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20161228_1503.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20161228_1503.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20170115_2258.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20170115_2258_1.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20170115_2258.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20170115_2258_2.txt 2017
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
 
echo "Chargement de CA20170424_1902-2016.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/A20170424_1902-2016.txt 2016
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20170424_1902-2017.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20170424_1902-2017.txt 2017
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20170424_1902-2017.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA.txt 2017
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180107_2017_2017.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180107_2017_2017.txt 2017
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180107_2017_2018.txt "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180107_2017_2018.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180125_1954.txt  "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180125_1954.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180205_1954.txt  "
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180205_1959.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180224_1817.txt"
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180224_1817_2018.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180328_2002.txt" 
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180328_2002.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20180422_1927-2018.txt" 
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20180422_1927-2018.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv

echo "Chargement de CA20181117_1611.txt" 
perl -w /home/frederickerdraon/Documents/researchwork/Perl/extractCashflows /home/frederickerdraon/Documents/researchwork/Data/CA20181117_1611.txt 2018
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview /home/frederickerdraon/Documents/researchwork/Datavalidated/cashflows.csv
