#!/bin/tcsh
set user1 = "root"
#echo $user1
#echo $PATH
#echo $shell
set RESEARCH = `pwd`
set dropfile = ~/Documents/researchwork/Sql/Mysql-drop.sql
#echo "Current directory :" $RESEARCH
set SQLDIR = $RESEARCH/Sql/
echo  "STEP - Backing up the checklists"
cd ./Perl
perl -w backChecks 
