#!/bin/tcsh
set user1 = "root"
#echo $user1
#echo $PATH
#echo $shell
set RESEARCH = `pwd`
set dropfile = ~/Documents/researchwork/Sql/Mysql-drop.sql
#echo "Current directory :" $RESEARCH
set SQLDIR = $RESEARCH/Sql/
echo "STEP - Truncate the tables"
mysql -u root -pfred1301 << EOF
use managementoverview;
truncate tools;
truncate skills;
truncate checks;
truncate contacts;
commit;
EOF
#truncate tasks;
echo "STEP - Import Tools..........."
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="\t" managementoverview $RESEARCH/Datavalidated/tools.csv
echo "STEP - Import Contacts..........."
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by=";" managementoverview $RESEARCH/Datavalidated/contacts.csv
echo "STEP - Import Skills..........."
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="\t" managementoverview $RESEARCH/Datavalidated/skills.csv
echo "STEP - Import Checks..........."
mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="," managementoverview $RESEARCH/Datavalidated/checks.csv
echo "STEP - Import Deliverables..........."
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --fields-terminated-by="\t" managementoverview $RESEARCH\Datavalidated\Deliverables.csv
echo "STEP - Import Tasks..........."
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="," managementoverview $RESEARCH/Datavalidated/tasks.csv
#cp -p $RESEARCH/Datavalidated/tasks1.csv $RESEARCH/Datavalidated/tasks.csv
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="," managementoverview $RESEARCH/Datavalidated/tasks.csv
#cp -p $RESEARCH/Datavalidated/tasks2.csv $RESEARCH/Datavalidated/tasks.csv
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="," managementoverview $RESEARCH/Datavalidated/tasks.csv
echo "STEP - Import Tasks other..........."
#mysqlimport -u root -pfred1301 -l -r --ignore-lines=1 --local --fields-terminated-by="," managementoverview $RESEARCH/Datavalidated/tasks1.csv

echo "STEP - Update complexity..........."
mysql -u root -pfred1301 managementoverview < $RESEARCH/Sql/MysqlUpdateComplexity.sql
echo "STEP - Mise a jour des donnees"

echo  "STEP - Generation des tableaux, graphs et camembers"
cd ./Perl
perl -w readTools
perl -w readResources
perl -w readTasks
perl -w readSkills
perl -w readTasksAggreg
perl -w readChecks
echo "STEP - Compilation du fichier latex"
cd ../Latex
pdflatex -interaction batchmode Project.tex
#pdflatex Project.tex
#cp -p Project.pdf ../../pdfs/RiskManagement/Project.pdf
