#!/bin/tcsh
set user1 = "root"
#echo $user1
#echo $PATH
#echo $shell
set RESEARCH = `pwd`
echo "STEP - Compilation du fichier latex"
cd ./Latex
pdflatex -interaction batchmode Letter.tex
#pdflatex Project.tex
#cp -p Project.pdf ../../pdfs/RiskManagement/Project.pdf
