#!/bin/bash

name=$1


email="frederickerdraon@gmail.com"
file=/home/frederickerdraon/Documents/researchwork/
subject=$1
file="$2"

echo "Sending file: $file"
echo "To: $email"
echo "Topics: $subject"



#df -h | mail -s “DiskSpaceReport” fredkerdraon@hotmail.com

mpack -s $subject $file $email
