select count(*),'ASSETS' from assets;
select count(*),'BALANCE' from balance;
select count(*), 'CASHFLOWS' from cashflows;
select count(*), 'CHECKS'  from checks;
select count(*), 'CONTACTS' from contacts;
select count(*), 'EVENTS' from events;
select count(*), 'KAPITAL' from kapital;
select count(*), 'SKILLS' from skills;
select count(*), 'STATS' from stats;
select count(*), 'STOCKS' from stocks;
select count(*), 'TASKS' from tasks;
select count(*), 'TOOLS' from tools;
select count(*), 'CURRENCIES' from currencies;
